const VENDOR_FEATURES = {
  huawei: [
    'onu-reboot',
    'onu-activate',
    'onu-deactivate',
    'onu-delete',
    'onu-description',
    'onu-line-profile',
    'onu-service-profile',
    'onu-alarm-profile',
    'onu-optical-info',
    'onu-distance',
    'onu-stats',
    'onu-eth-ports',
    'onu-vlan-config',
    'onu-fec',
    'onu-mac-limit',
    'onu-igmp',
    'onu-multicast-vlan',
    'onu-tcont',
    'onu-gemport',
    'onu-service',
    'onu-service-port',
    'onu-ip-host',
    'onu-loopback',
    'onu-alarm-config',
    'onu-video',
    'onu-vlan-filter',
    'onu-voip',
    'onu-add',
    'onu-autofind',
    'onu-autofind-confirm',
    'onu-batch-activate',
    'onu-batch-deactivate',
    'onu-batch-reboot',
    'onu-batch-profile',
    'onu-upgrade-firmware',
    'config-system',
    'config-vlans',
    'config-pon',
    'config-profiles',
    'config-routes',
    'config-snmp',
    'config-tr069',
    'config-gps',
    'onuview-info',
    'onuview-optical',
    'onuview-eth',
    'onuview-stats',
    'onuview-config',
    'onuview-actions',
    'system-backup',
    'system-firmware',
    'system-users',
    'system-ntp',
    'system-snmp',
    'system-syslog',
    'dashboard-kpi-cards',
    'dashboard-charts',
    'dashboard-pon-status',
  ],

  kingtype: [
    'onu-reboot',
    'onu-activate',
    'onu-deactivate',
    'onu-delete',
    'onu-description',
    'onu-line-profile',
    'onu-service-profile',
    'onu-alarm-profile',
    'onu-optical-info',
    'onu-distance',
    'onu-stats',
    'onu-eth-ports',
    'onu-vlan-config',
    'onu-fec',
    'onu-mac-limit',
    'onu-igmp',
    'onu-multicast-vlan',
    'onu-tcont',
    'onu-gemport',
    'onu-service',
    'onu-service-port',
    'onu-ip-host',
    'onu-loopback',
    'onu-alarm-config',
    'onu-vlan-filter',
    'onu-add',
    'onu-autofind',
    'onu-autofind-confirm',
    'onu-batch-activate',
    'onu-batch-deactivate',
    'onu-batch-reboot',
    'onu-batch-profile',
    'onu-upgrade-firmware',
    'config-system',
    'config-vlans',
    'config-pon',
    'config-profiles',
    'config-routes',
    'config-snmp',
    'onuview-info',
    'onuview-optical',
    'onuview-eth',
    'onuview-stats',
    'onuview-config',
    'onuview-actions',
    'system-backup',
    'system-firmware',
    'system-users',
    'system-ntp',
    'system-syslog',
    'dashboard-kpi-cards',
    'dashboard-charts',
    'dashboard-pon-status',
  ],

  vsol: [
    'onu-reboot',
    'onu-activate',
    'onu-deactivate',
    'onu-delete',
    'onu-description',
    'onu-line-profile',
    'onu-service-profile',
    'onu-alarm-profile',
    'onu-optical-info',
    'onu-distance',
    'onu-stats',
    'onu-eth-ports',
    'onu-vlan-config',
    'onu-fec',
    'onu-mac-limit',
    'onu-igmp',
    'onu-multicast-vlan',
    'onu-tcont',
    'onu-gemport',
    'onu-service',
    'onu-service-port',
    'onu-ip-host',
    'onu-loopback',
    'onu-alarm-config',
    'onu-vlan-filter',
    'onu-add',
    'onu-autofind',
    'onu-autofind-confirm',
    'onu-batch-activate',
    'onu-batch-deactivate',
    'onu-batch-reboot',
    'onu-batch-profile',
    'onu-upgrade-firmware',
    'config-system',
    'config-vlans',
    'config-pon',
    'config-profiles',
    'config-routes',
    'config-snmp',
    'onuview-info',
    'onuview-optical',
    'onuview-eth',
    'onuview-stats',
    'onuview-config',
    'onuview-actions',
    'system-backup',
    'system-firmware',
    'system-users',
    'system-ntp',
    'system-syslog',
    'dashboard-kpi-cards',
    'dashboard-charts',
    'dashboard-pon-status',
  ],
}

export function getSupported(brand) {
  const key = (brand || '').toLowerCase()
  return VENDOR_FEATURES[key] || VENDOR_FEATURES.huawei
}

export function isSupported(brand, feature) {
  return getSupported(brand).includes(feature)
}

export function filterByVendor(brand, items, featureKey = 'feature') {
  const supported = getSupported(brand)
  return items.filter(item => supported.includes(item[featureKey]))
}

export function unsupportedReason(brand, feature) {
  const msgs = {
    'config-tr069': 'TR-069 ACS no disponible en ' + brand + ' — la OLT no tiene ACS integrado. Las ONUs pueden ser gestionadas vía OMCI o plataforma externa (AdminOLT, FriendlyTech).',
    'config-gps':   'GPS / ubicación no disponible en ' + brand + ' — esta OLT no tiene GPS integrado. Para geolocalización, usa coordenadas manuales.',
    'onu-video':    'CATV/Video no soportado en ' + brand + ' — esta OLT/ONU no tiene salida de video RF.',
    'onu-voip':     'VoIP no soportado en este modelo de ONU — verificar compatibilidad.',
    'onu-upgrade-firmware': 'Actualización de firmware no disponible por CLI en esta OLT — usar interfaz web.',
  }
  return msgs[feature] || 'Función no disponible en ' + brand
}

export default VENDOR_FEATURES
